### ISSUE TITLE
Feature request: block copy and pasting 

### ISSUE THREAD

**Issue by traveller-kino** [RupertBenWiser/Web-Environment-Integrity#61]
I don't want people to highlight text, copy, or paste into my site, and this is too easily bypassed with user scripts, so it should be TPM enforced

**Comment by zb3** [comment]
Great idea, but we also need to consider malicious users manually rewriting the text using their keyboard. That should not be allowed and my proposal'd be to send both the visited website and every user keystroke (including those outside browser windows) to Google so that they can be analysed and the user which dares to manually rewrite a given text without author's permission should be punished.

**Comment by Howdoesthiswo** [comment]
Why are we letting people use the web at all? Just implement a mandatory "Google fee" on everyone that breathes. No browser code to write or maintain, the implementation is easy as there's already tax collection mechanisms in government that can be taken over by bribing legislative bodies (excuse me, I mean by giving "campaign contributions"), and its guaranteed revenue that is nearly 100% profit.

**Comment by lunaneff** [comment]
Let's also add a system where users can pay a small fee of only $14.99 a month for the privilege of copying 5 words, with an additional $5 per extra word copied. Website owners would get $0.001 per word, while Google receives the rest.
